### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by zerox1212** [jdsaund/dynamic-balancer#2]
Do you have a write up, guide, or example showing how this works?

**Comment by jdsaund** [comment]
I wish I did. This is something I've been meaning to do for a while, but haven't yet. It's based off a Goertzel algorithm that I have modified to self scale in real time. If there is anything specific you'd like to know feel free to ask

**Comment by zerox1212** [comment]
What was your application? What did you use this device to balance?

**Comment by jdsaund** [comment]
I have an autonomous helicopter that has a high powered brushless motor and several moving parts. I needed something to give me an indication of where the imbalance lies rather than spending hours using trial and error.

I guess I was aiming to develop something that can balance motors at extremely high RPM, as I couldn't find anything out there that could. The only brushless motor balancers on the market only work at 1000rpm, which is too slow for very accurate balancing as a small magnitude of imbalance gets more difficult to detect the slower you go.

The balancer can be used to balance anything in a single plane, but the sample cache and accelerometer you choose to use are what will dictate the limitations of your setup. An MPU6000 will have a limit of 15000rpm and +/-16g which is good for small brushless motors. I found 10000 rpm to be best for small brushless motors. There is no reason you couldn't expand the cache to be suitable for larger and slower motors too.

The process of balancing used an eccentric mass (like a zip tie) and two (or three I can't remember) passes to detect the magnitude and phase of the imbalance. The program actually does all the calculations for you so you don't need to understand the theory behind it.

**Comment by zerox1212** [comment]
I am working on a low cost tire balancer for car tires used for racing. Having to pay a shop to mount and balance tires gets very expensive.

I have read several documents on two plane dynamic balancing, but this is the first time I read about the Goertzel algorithm. I don't know if it will work, but I was hoping to achieve a reasonable balance by hand spinning the tire, so the RPMs would be low (like 30 rpm).

**Comment by jdsaund** [comment]
It's possible but the lower the rpm the more susceptible to noise you'll be. Same for too fast. 

Probably the most important thing is to spin the object at exactly the same RPM for each pass, as there are complicated phase shifts that occur with different RPMs. By keeping the same speed for each pass, the code can filter it out.

It would be best to use a closed loop controller for spinning the wheel with a motor (pid controlled with a tachometer for feedback). That way you'll know you have the exact same RPM each time. Youll be surprised how much the motor/wheel changes it's speed with different balance without closed loop control. I used the governor on my motor speed controller to keep the motors spinning the same speed.

**Comment by zerox1212** [comment]
Thanks for the advice. I hope to design some kind of affordable option. If you have ever watched how a professional tire balancer works it does not spin the tire very fast. At the moment I don't know how they achieve balancing with this method, but I can't imagine it's that difficult as tire balancers have been around for a really long time. It seems crazy that a new one can still cost $7000.

**Comment by kinglevel** [comment]
Wonderful code!

someone should fork this and update it with 2 plane! That would be a game changer for diy balancers
